name: Babys First Workflow

# Controls when the workflow will run
on:
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    contents: read

# Workflow jobs can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs latest stable version of python
      - uses: actions/setup-python@v5
        with:
            python-version: '3.x'

      - name: Install pip dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Download updated METARS data
        run: python src/metars.py

      - name: Commit updated METARS data
        run: |
            git config --global user.name 'Weather Bob'
            git config --global user.email 'weather-bob@users.noreply.github.com'
            git commit -am "Update METARS data"
            git push
