name: Babys First Workflow

# Controls when the workflow will run
on:
  # Schedule workflow to run daily
  schedule:
    - cron: '20 4 * * *'
  # Run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    contents: write

# Workflow jobs can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Installs latest stable version of python
      - uses: actions/setup-python@v5
        with:
            python-version: '3.x'

      - name: Install pip dependencies
        run: |
            python -m pip install --upgrade pip
            if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi

      - name: Download updated METARS data
        run: python src/metars.py

      - name: Commit updated METARS data
        run: |
            git config --global user.name $GIT_USER
            git config --global user.email $GIT_EMAIL
            git commit -am $GIT_COMMIT_MSG
            git push
        env:
            GIT_USER: 'Weather Bob'
            GIT_EMAIL: 'weather-bob@users.noreply.github.com'
            GIT_COMMIT_MSG: 'Update METARS data'
